### ISSUE TITLE
DevOps: CI/CDパフォーマンステスト・アクセシビリティ監査自動化

### ISSUE THREAD

**Issue by Otoriha** [Otoriha/Tiramisu-app#63]
## 🎯 目的

GitHub ActionsでPlaywright-Lighthouseを使用したパフォーマンステストとアクセシビリティ監査を自動化し、継続的な品質保証を実現します。

## 📊 現状の課題

- パフォーマンステストが手動実行のみ
- アクセシビリティチェックが開発時のみ
- 品質の後戻りが検知しにくい
- チーム全体での品質基準統一が困難

### 1. GitHub Actions ワークフロー作成
```yaml
# .github/workflows/quality-check.yml
name: Quality Check (Performance & Accessibility)

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  schedule:
    - cron: '0 2 * * 1' # 毎週月曜日 2:00 AM

jobs:
  performance-test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: |
          npm ci
          cd frontend && npm ci
          
      - name: Build application
        run: cd frontend && npm run build
        
      - name: Install Playwright
        run: cd frontend && npx playwright install --with-deps
        
      - name: Start application
        run: |
          cd frontend && npm run preview &
          sleep 10
        
      - name: Run performance tests
        run: cd frontend && npm run test:performance
        
      - name: Run accessibility tests
        run: cd frontend && npm run test:accessibility
        
      - name: Upload reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: quality-reports
          path: |
            frontend/playwright-report-performance/
            frontend/playwright-report-accessibility/
            frontend/lighthouse-reports/
            
  lighthouse-audit:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Lighthouse CI
        uses: treosh/lighthouse-ci-action@v10
        with:
          configPath: './frontend/lighthouserc.json'
          uploadArtifacts: true
          temporaryPublicStorage: true
```

### 2. Lighthouse CI設定
```json
// frontend/lighthouserc.json
{
  "ci": {
    "collect": {
      "url": [
        "http://localhost:5173/",
        "http://localhost:5173/about",
        "http://localhost:5173/search",
        "http://localhost:5173/recipes",
        "http://localhost:5173/contact"
      ],
      "startServerCommand": "npm run preview",
      "startServerReadyPattern": "Local:.*:(\\d+)",
      "startServerReadyTimeout": 10000
    },
    "assert": {
      "preset": "lighthouse:recommended",
      "assertions": {
        "categories:performance": ["error", {"minScore": 0.85}],
        "categories:accessibility": ["error", {"minScore": 0.95}],
        "categories:best-practices": ["error", {"minScore": 0.90}],
        "categories:seo": ["error", {"minScore": 0.90}]
      }
    },
    "upload": {
      "target": "temporary-public-storage"
    }
  }
}
```

### 3. パフォーマンス監視スクリプト
```typescript
// scripts/performance-monitor.ts
import { chromium } from 'playwright';
import { readFileSync, writeFileSync } from 'fs';

interface PerformanceMetrics {
  url: string;
  timestamp: string;
  metrics: {
    FCP: number;
    LCP: number;
    CLS: number;
    FID: number;
    loadTime: number;
    bundleSize: number;
  };
}

export async function collectPerformanceMetrics(urls: string[]): Promise<PerformanceMetrics[]> {
  const browser = await chromium.launch();
  const results: PerformanceMetrics[] = [];

  for (const url of urls) {
    const page = await browser.newPage();
    
    // Lighthouse メトリクス収集
    const metrics = await page.evaluate(() => {
      const navigation = performance.getEntriesByType('navigation')[0] as PerformanceNavigationTiming;
      const paintEntries = performance.getEntriesByType('paint');
      
      return {
        loadTime: navigation.loadEventEnd - navigation.loadEventStart,
        FCP: paintEntries.find(entry => entry.name === 'first-contentful-paint')?.startTime || 0,
        // 他のメトリクス...
      };
    });

    results.push({
      url,
      timestamp: new Date().toISOString(),
      metrics: {
        ...metrics,
        LCP: 0, // Lighthouse からの値
        CLS: 0, // Lighthouse からの値
        FID: 0, // Lighthouse からの値
        bundleSize: 0, // ビルド後のサイズ
      }
    });

    await page.close();
  }

  await browser.close();
  return results;
}
```

### 4. パフォーマンスレポート生成
```typescript
// scripts/generate-performance-report.ts
export function generatePerformanceReport(metrics: PerformanceMetrics[]) {
  const report = {
    generatedAt: new Date().toISOString(),
    summary: {
      totalPages: metrics.length,
      averageLoadTime: metrics.reduce((sum, m) => sum + m.metrics.loadTime, 0) / metrics.length,
      passedThreshold: metrics.filter(m => m.metrics.loadTime < 3000).length,
    },
    pages: metrics,
    recommendations: generateRecommendations(metrics),
  };

  writeFileSync('performance-report.json', JSON.stringify(report, null, 2));
  generateMarkdownReport(report);
}

function generateRecommendations(metrics: PerformanceMetrics[]): string[] {
  const recommendations: string[] = [];
  
  metrics.forEach(metric => {
    if (metric.metrics.FCP > 2000) {
      recommendations.push(`${metric.url}: First Contentful Paint を改善してください (現在: ${metric.metrics.FCP}ms)`);
    }
    if (metric.metrics.LCP > 2500) {
      recommendations.push(`${metric.url}: Largest Contentful Paint を改善してください (現在: ${metric.metrics.LCP}ms)`);
    }
  });

  return recommendations;
}
```

### 5. アクセシビリティ監査自動化
```typescript
// tests/accessibility-ci.spec.ts
import { test, expect } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';

const pages = [
  { url: '/', name: 'Home' },
  { url: '/about', name: 'About' },
  { url: '/search', name: 'Search' },
  { url: '/recipes', name: 'Recipes' },
  { url: '/contact', name: 'Contact' },
];

for (const page of pages) {
  test(`${page.name} ページのアクセシビリティ`, async ({ page: browserPage }) => {
    await browserPage.goto(page.url);
    
    const results = await new AxeBuilder({ page: browserPage })
      .withTags(['wcag2a', 'wcag2aa', 'wcag21aa'])
      .analyze();
    
    expect(results.violations).toHaveLength(0);
    
    // 詳細レポート生成
    if (results.violations.length > 0) {
      console.log(`アクセシビリティ違反が見つかりました (${page.name}):`);
      results.violations.forEach(violation => {
        console.log(`- ${violation.id}: ${violation.description}`);
        console.log(`  影響: ${violation.impact}`);
        console.log(`  要素数: ${violation.nodes.length}`);
      });
    }
  });
}
```

### 6. package.json スクリプト追加
```json
{
  "scripts": {
    "test:performance:ci": "playwright test --config=playwright.performance.config.ts --reporter=html",
    "test:accessibility:ci": "playwright test tests/accessibility-ci.spec.ts --reporter=html",
    "lighthouse:ci": "lhci autorun",
    "quality:check": "npm run test:performance:ci && npm run test:accessibility:ci && npm run lighthouse:ci",
    "performance:monitor": "ts-node scripts/performance-monitor.ts",
    "report:generate": "ts-node scripts/generate-performance-report.ts"
  }
}
```

## 📁 追加・変更ファイル

- `.github/workflows/quality-check.yml` - CI/CDワークフロー
- `frontend/lighthouserc.json` - Lighthouse設定
- `scripts/performance-monitor.ts` - パフォーマンス監視
- `scripts/generate-performance-report.ts` - レポート生成
- `tests/accessibility-ci.spec.ts` - アクセシビリティCI
- `package.json` - 新スクリプト追加

## 📋 実装手順

1. **依存関係追加**
   ```bash
   npm install --save-dev @lhci/cli @axe-core/playwright
   ```

2. **GitHub Actions設定**
   - ワークフロー作成
   - シークレット設定（必要に応じて）

3. **Lighthouse CI設定**
   - 設定ファイル作成
   - しきい値設定

4. **監視スクリプト実装**
   - パフォーマンス収集
   - レポート生成

## ✅ 受け入れ基準

- [ ] PR作成時に自動的にパフォーマンステストが実行される
- [ ] アクセシビリティ監査が自動実行される
- [ ] Lighthouseスコアがしきい値を下回った場合にCIが失敗する
- [ ] 詳細なレポートがアーティファクトとして保存される
- [ ] 週次での定期監査が実行される
- [ ] パフォーマンス履歴が追跡可能
- [ ] チーム全体で結果が共有される

## 🧪 テスト方法

1. **CI/CD動作確認**
   ```bash
   # ローカルでのCI模擬実行
   npm run quality:check
   ```

2. **PR作成でのテスト**
   - テスト用PRでワークフロー確認
   - 失敗ケースの動作確認

3. **定期実行の確認**
   - スケジュール実行の動作確認

## 📈 期待される効果

- **品質保証**: 自動的な品質監視
- **早期発見**: パフォーマンス劣化の早期検知
- **チーム効率**: 手動テストの削減
- **継続改善**: データに基づく改善計画
- **リグレッション防止**: 既存機能の品質維持

### パフォーマンス
- Lighthouse Performance Score (>85)
- First Contentful Paint (<2.0s)
- Largest Contentful Paint (<2.5s)
- Cumulative Layout Shift (<0.1)

### アクセシビリティ
- WCAG 2.1 AA準拠 (100%)
- Lighthouse Accessibility Score (>95)
- 違反件数 (0件)

## 🔗 関連Issue

- 全ての最適化Issue（監視対象）
- パフォーマンス改善（効果測定）

## 🏷️ 技術詳細

- **影響範囲**: CI/CD・品質保証全体
- **リスク**: 低（既存機能に影響なし）
- **作業時間**: 4-5時間
- **継続保守**: 定期的なしきい値見直し
